id: P000367
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD90002
  title: དཔལ་ཡུལ་རྫོང་གི་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  volumes:
    02ade8f3c97343fbba642103ba740d6c:
      image_group_id: I1PD90051
      title: Volume 1 of bai yu xian zhi
      volume_number: 1
      total_pages: 616
      base_file: v001.txt
