id: P000367
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90002
  title: དཔལ་ཡུལ་རྫོང་གི་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  volumes:
    02ade8f3c97343fbba642103ba740d6c:
      image_group_id: I1PD90051
      title: Volume 1 of bai yu xian zhi
      volume_number: 1
      total_pages: 616
      base_file: v001.txt
ebook_metadata:
  title: དཔལ་ཡུལ་རྫོང་གི་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  sku: P000367
  cover: cover.jpg
  layers:
  - pagination
